payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    path('', views.home, name='home'),
    path("addorder/", views.add_order),
    path("orders/<pk>/", views.get_orders),
    path('create/', views.create_payment, name='create_payment'),
    path('invoice/<pk>/', views.track_invoice, name='track_payment'),
    path('receive/', views.receive_payment, name='receive_payment'),
    path("users/", views.get_users, name="users"),
    path("users/banned/", views.get_banned_users),
    path("user/<pk>/", views.get_user, name="user"),
    path("createuser/", views.create_user),
    path("products/", views.get_products),
    path("product/<pk>/", views.get_product),
    path("invoices/", views.get_invoices),
    path("invoice/<pk>/", views.get_invoice),
    path("ban/", views.ban_user),
    path("unban/", views.unban_user),
    path("status/", views.change_status),
    path("balance/", views.update_user_balance),
    path("deleteproduct/", views.delete_product),
    path("createproduct/", views.create_product),
    path("updateproduct/", views.update_product),
    path("createcoupon/", views.create_coupon),
    path("coupons/", views.get_coupons),
    path("coupons/delete/", views.delete_coupon),
    path("createvipcoupon/", views.create_vipcoupon),
    path("vipcoupons/", views.getvip_coupons),
    path("vipcoupons/delete/", views.deletevip_coupon),
    path("usersdump/", views.users_dump),
    path("coupon/<code>/", views.get_coupon),
    path("createorder/", views.create_order),
    path("markcoupon/", views.mark_coupon),
    path("pendingorders/<user_id>/", views.pending_users_orders),
    path("settledorders/<user_id>/", views.settled_users_orders),
    path("approveorders/", views.approve_order),
    path("transactiontoday/", views.transactions_today),
    path("transactionweekly/", views.transactions_weekly),
    path("transactionmonthly/", views.transactions_monthly),
    path("transactionall/", views.transactions_all)
]

sms/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('payment/', include("payments.urls"))
]

payments/models.py
import datetime
import uuid
from django.utils import timezone
from django.db import models
from django.contrib.auth import get_user_model

UserModel = get_user_model()


def product_image_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/actual/<filename>
    return "actual/{0}".format(filename)


def product_thumb_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/thumb/<filename>
    return "thumb/{0}".format(filename)


def gen_id():
    return uuid.uuid4().int


def gen_id2():
    return uuid.uuid4().hex


class Product(models.Model):
    product_id = models.CharField(max_length=50, default=gen_id)
    title = models.CharField(max_length=50)
    description = models.TextField()
    price = models.FloatField()
    volume = models.IntegerField(default=1, blank=True)
    minimumQty = models.IntegerField(default=1)

    def __str__(self):
        return self.title


class Coupon(models.Model):
    code = models.CharField(max_length=100)
    discount = models.FloatField()
    used = models.BooleanField(default=False)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.code


class VIPCoupon(models.Model):
    code = models.CharField(max_length=100)
    discount = models.FloatField()
    used = models.BooleanField(default=False)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        ordering = "date_added",

    def __str__(self):
        return self.code


class Order(models.Model):
    order_id = models.CharField(max_length=100, default=gen_id)
    user = models.ForeignKey(UserModel, on_delete=models.SET_NULL, blank=True, null=True, related_name="orders")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="products")
    coupon = models.ForeignKey(Coupon, blank=True, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=1)  # quantity for the product
    date = models.DateField(default=timezone.now)
    settled = models.BooleanField(default=False)

    @property
    def actual_price(self):
        self.product: Product
        self.coupon: Coupon
        if self.coupon:
            right = self.quantity * self.product.price
            left = self.quantity * self.product.price * self.coupon.discount
            return right - left
        return self.quantity * self.product.price


class Invoice(models.Model):
    STATUS_CHOICES = (
        (-1, "Not Started"),
        (0, "Unconfirmed"),
        (1, "Partially Confirmed"),
        (2, "Confirmed"),
    )
    created_by = models.ForeignKey(UserModel, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey("Product", on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUS_CHOICES, default=-1)
    order_id = models.CharField(max_length=250)
    address = models.CharField(max_length=250, blank=True, null=True)
    btcvalue = models.IntegerField(blank=True, null=True)
    received = models.IntegerField(blank=True, null=True)
    txid = models.CharField(max_length=250, blank=True, null=True)
    rbf = models.IntegerField(blank=True, null=True)
    created_at = models.DateField(auto_now=True)
    rate = models.FloatField(default=0, blank=True)
    settled = models.BooleanField(default=False)

    def __str__(self):
        return self.address


class Transaction(models.Model):
    STATUS_CHOICES = (
        (-1, "Not Started"),
        (0, "Unconfirmed"),
        (1, "Partially Confirmed"),
        (2, "Confirmed"),
    )
    amount = models.FloatField()
    created_by = models.ForeignKey(UserModel, on_delete=models.CASCADE, null=True, related_name="transactions")
    status = models.IntegerField(choices=STATUS_CHOICES, default=-1)
    order_id = models.CharField(max_length=250)
    address = models.CharField(max_length=250, blank=True, null=True)
    btcvalue = models.FloatField(blank=True, null=True)
    received = models.FloatField(blank=True, null=True)
    txid = models.CharField(max_length=250, blank=True, null=True)
    rbf = models.IntegerField(blank=True, null=True)
    created_at = models.DateField(default=datetime.date.today)
    rate = models.FloatField(default=0, blank=True)
    settled = models.BooleanField(default=False)


class ServiceOrder(models.Model):
    order_id = models.CharField(max_length=200, default=gen_id2)
    service = models.CharField(max_length=10)
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    qty = models.IntegerField(default=0)
    user = models.IntegerField()
    date_added = models.DateTimeField(default=datetime.date.today)
    link = models.CharField(max_length=200)
    source = models.IntegerField(default=0)

payments/views.py
import datetime
from datetime import timedelta
import os
from pathlib import Path
import django.http as http
import telegram
from django.http.response import JsonResponse
from django.shortcuts import render, reverse
from django.http import HttpResponse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from accounts.models import MyUser
from django.core.serializers import serialize
from .models import Invoice
from .models import Coupon
from .models import Product
from .models import Transaction
from .models import Order
from .models import VIPCoupon
from .models import ServiceOrder
import requests
import uuid
import toml

BASE_DIR = Path(__file__).resolve().parent.parent


def home(request):
    products = Product.objects.all()
    return render(request, "product.html", context={"products": products})


@csrf_exempt
def add_order(request: http.HttpRequest):
    if request.method != "POST":
        return JsonResponse({"error": "method not allowed"})
    qty = request.POST.get("qty")
    name = request.POST.get("name")
    category = request.POST.get("category")
    link = request.POST.get("link")
    service = request.POST.get("service")
    user = request.POST.get("user_id")
    source = request.POST.get("source")
    order = ServiceOrder.objects.create(
        service=service, name=name, category=category, qty=qty, user=user, link=link, source=source
    )
    order.save()
    return JsonResponse({"order": order.pk})


def get_orders(request: http.HttpRequest, pk):
    if request.method != "GET":
        return JsonResponse({"error": "method not allowed"})
    orders: list[ServiceOrder] = ServiceOrder.objects.filter(user=pk)
    info = []
    for order in orders:
        data = {}
        attrs = ["name", "service", "link", "qty", "order_id"]
        for attr in attrs:
            data[attr] = getattr(order, attr)
        info.append(data)
    return JsonResponse({"orders": info})


def get_order_status(request: http.HttpRequest, user, pk):
    if request.method != "GET":
        return JsonResponse({"error": "method not allowed"})
    try:
        order: ServiceOrder = ServiceOrder.objects.get(user=user, order_id=pk)
        source = order.source
        if source == 1:
            """smmstone"""

        elif source == 2:
            """crescitaly"""
    except Exception:
        pass
# ------------------- Coupon Views ---------------------------


@csrf_exempt
def create_coupon(request: http.HttpRequest):
    if request.method != "POST":
        return JsonResponse({"error": "method not allowed"})
    code = request.POST.get("code")
    discount = request.POST.get("discount")
    coupon = Coupon.objects.get_or_create(code=code)[0]
    coupon.discount = discount
    coupon.save()
    msg = "Coupon created"
    return JsonResponse({"msg": msg})


@csrf_exempt
def create_vipcoupon(request: http.HttpRequest):
    if request.method != "POST":
        return JsonResponse({"error": "method not allowed"})
    code = request.POST.get("code")
    discount = request.POST.get("discount")
    coupon = VIPCoupon.objects.get_or_create(code=code)[0]
    coupon.discount = discount
    coupon.save()
    msg = "Coupon created"
    return JsonResponse({"msg": msg})


@csrf_exempt
def delete_coupon(request: http.HttpRequest):
    if request.method != "POST":
        return JsonResponse({"error": "method not allowed"})
    code = request.POST.get("code")
    coupon = Coupon.objects.get(code=code)
    coupon.delete()
    msg = "Coupon deleted"
    return JsonResponse({"msg": msg})


@csrf_exempt
def deletevip_coupon(request: http.HttpRequest):
    if request.method != "POST":
        return JsonResponse({"error": "method not allowed"})
    code = request.POST.get("code")
    coupon = Coupon.objects.get(code=code)
    coupon.delete()
    msg = "Coupon deleted"
    return JsonResponse({"msg": msg})


def get_coupons(request: http.HttpRequest):
    res = serialize("json", Coupon.objects.filter(used=False), fields=["code", 'discount'])
    return JsonResponse({"coupons": res})


def get_coupon(request: http.HttpRequest, code):
    try:
        coupon = Coupon.objects.get(code=code)
    except Exception as e:
        res = []
    else:
        res = {"code": coupon.code, "discount": coupon.discount, "used": coupon.used}
    return JsonResponse({"coupon": res})


def getvip_coupons(request: http.HttpRequest):
    res = serialize("json", [VIPCoupon.objects.order_by("date_added")[-1]], fields=["code", 'discount'])
    return JsonResponse({"coupons": res})


@csrf_exempt
def mark_coupon(request: http.HttpRequest):
    if request.method != "POST":
        return JsonResponse({"error": "method not allowed"})
    code = request.POST.get("code")
    coupon: Coupon = Coupon.objects.get(code=code)
    coupon.count += 1
    coupon.save()
    return JsonResponse({"count": coupon.count})


# ----------------------- User Views -----------------------------
def get_users(request: http.HttpRequest):
    data = []
    users = MyUser.objects.filter(banned=False)
    fields = ["telegram_id", "balance", "status", "fname", "username"]
    for user in users:
        info = {}
        for field in fields:
            info[field] = getattr(user, field)
        data.append(info)
    return JsonResponse({"users": data})


def get_banned_users(request: http.HttpRequest):
    users = serialize(
        "json", MyUser.objects.filter(banned=True),
        fields=["telegram_id", "balance", "status", "fname"]
    )
    return JsonResponse({"users": users})


def get_user(request: http.HttpRequest, pk):
    try:
        user: MyUser = MyUser.objects.get(pk=pk)
    except Exception:
        return JsonResponse({"user": {}})
    balance = user.balance
    banned = user.banned
    fname = user.fname
    username = user.username
    discount = user.discount
    status = "VIP" if user.status == "vip" else "Regular"
    telegram_id = user.telegram_id
    trans_count = user.transactions.count()
    trans_paid = user.transactions.filter(settled=True).count()
    trans_unpaid = user.transactions.filter(settled=False).count()
    orders_count = user.orders.count()
    orders_approved = user.orders.filter(settled=True).count()
    orders_unapproved = user.orders.filter(settled=False).count()
    info = {
        "fname": fname, "username": username, "discount": discount, "banned": banned,
        "balance": balance, "status": status, "telegram_id": telegram_id, "trans_count": trans_count,
        "trans_unpaid": trans_unpaid, "trans_paid": trans_paid, "orders_count": orders_count,
        "orders_approved": orders_approved, "orders_unapproved": orders_unapproved
    }
    return JsonResponse({"user": info})


@csrf_exempt
def create_user(request: http.HttpRequest):
    if request.method != "POST":
        return JsonResponse({"error": "method not allowed"})
    telegram_id = request.POST.get("user_id")
    fname = request.POST.get("fname")
    username = request.POST.get("username")
    try:
        user = MyUser.objects.get(
            telegram_id=telegram_id
        )
    except Exception as e:
        user = MyUser.objects.create_user(
            telegram_id=telegram_id, password="default", fname=fname, username=username
        )
        user.save()
    return get_user(request, user.telegram_id)


@csrf_exempt
def ban_user(request: http.HttpRequest):
    if request.method != "POST":
        return JsonResponse({"error": "method not allowed"})
    pk = request.POST.get("user_id")
    lang = request.POST.get("loc", "")
    user = MyUser.objects.get(telegram_id=pk)
    user.banned = True
    user.save()
    msg = "user banned" if lang == "en" else "user banned"
    return JsonResponse({"msg": msg})


@csrf_exempt
def unban_user(request: http.HttpRequest):
    if request.method != "POST":
        return JsonResponse({"error": "method not allowed"})
    pk = request.POST.get("user_id")
    lang = request.POST.get("loc", "")
    user = MyUser.objects.get(telegram_id=pk)
    user.banned = False
    user.save()
    msg = "user unbanned" if lang == "en" else "User unbanned"
    return JsonResponse({"msg": msg})


@csrf_exempt
def change_status(request: http.HttpRequest):
    if request.method != "POST":
        return JsonResponse({"error": "method not allowed"})
    pk = request.POST.get("user_id")
    user = MyUser.objects.get(telegram_id=pk)
    user.status = "regular" if user.status == "vip" else "vip"
    user.save()
    msg = "user status changed"
    return JsonResponse({"msg": msg})


def users_dump(request: http.HttpRequest):
    users = MyUser.objects.filter(banned=False)
    data = []
    for user in users:
        user: MyUser
        info = {"username": user.username, "id": user.telegram_id}
        data.append(info)
    return JsonResponse({"users": data})


@csrf_exempt
def update_user_balance(request: http.HttpRequest):
    if request.method != "POST":
        return JsonResponse({"error": "method not allowed"})
    pk = request.POST.get("user_id")
    amount = request.POST.get("amount")
    deduct = request.POST.get("charge")
    user = MyUser.objects.get(telegram_id=pk)
    if deduct:
        user.balance -= float(amount)
    else:
        user.balance += float(amount)
    user.save()
    return JsonResponse({"msg": "OK"})


# ------------------------ Product Views --------------------------

def get_products(request: http.HttpRequest):
    products = serialize("json", Product.objects.all())
    return JsonResponse({"products": products})


@csrf_exempt
def create_product(request: http.HttpRequest):
    if request.method != "POST":
        return JsonResponse({"error": "method not allowed"})
    price = request.POST.get("price")
    description = request.POST.get("desc")
    title = request.POST.get("name")
    volume = request.POST.get("volume")
    try:
        prod = Product.objects.create(price=price, description=description, title=title, volume=volume)
    except Exception as e:
        print(e)

payments/templates/invoice.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <title>Blockonomics</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Blockonomics Payment API Demo</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'payments:home' %}">Products</a>
              </li>
              
            </ul>
          </div>
        </div>
      </nav>
      <div class="container">
        <h4 class="title is-4">Order#: {{order_id}}</h4>
        <hr>     
        <div class="row">
            <div id="paymentstatus" style="color:blue;display:true;">Payment Status: {{status}}</div>
            <div class="col-md-6 col-sm-12">
            <p>Amount: <strong>{{bits}}</strong> BTC ⇌ <strong>{{value}}</strong> USD</p>
            <p>Bitcoin Address : <strong>{{addr}}</strong></p>
            <a href="bitcoin:{{addr}}?amount={{bits}}">
                <img src="https://www.bitcoinqrcodemaker.com/api/?style=bitcoin&address={{addr}}&amount={{bits}}&color=1">
            </a>   
            </div>
            <div class="col-md-6 col-sm-12">
                <h4 class="subtitle">Order Details: </h4>
                <table class="table">
                <tbody>
                    <tr>
                    <td>HD DSLR Image- Himalaya</td>
                    <td>x 1</td>
                    <td>${{value}}</td>
                    </tr>
                    <tr>
                    <td colspan="2" align=left><strong>Total:</strong></td>
                    <td><strong>${{value}}</strong></td>
                    </tr>
                    <tr>
                      <td colspan="2" align=left><strong>Paid Bitcoins:</strong></td>
                      <td><strong>{{paid}}</strong></td>
                      </tr>
                    
                </tbody>
                </table>
                {% if path %}
                <div>
                    <img id="my_image" src='{{path}}'>
                </div>
                {% endif %}
            </div>
        </div>
      </div>
      <script type="text/javascript">
        var address="{{addr}}";
        var status="{{invoice_status}}";
      </script>
      <script type="text/javascript" src="{% static 'js/invoice.js' %}"></script>
      
</body>
</html>

payments/templates/product.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <title>Blockonomics</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Blockonomics Payment API Demo</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'payments:home' %}">Products</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    <div class="container-fluid">
        <h1> Products for Showcase!</h1>
        {% for product in products %}
            <div class='row'>
                <div class='col-lg-3'>
                    <div class="card-group">
                        <div class="card">
                        <img src="{{product.product_thumb.url}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{product.title}}</h5>
                            <p class="card-text">{{product.description}}</p>
                            <input hidden name="id" value="{{product.id}}">
                            <p class="card-text"><a href="{% url 'payments:create_payment' pk=product.id %}"><button class="btn btn-primary">Price: {{product.price}} USD</button></a></p>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>